server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: gunay
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.PostgreSQL95Dialect
      properties:
        hibernate:
          temp:
            use_jdbc-metadata_defaults: false


